version: '3.8'

services:
  app:
    build: .
    container_name: pm_api
    ports:
      - "8080:8080"
    env_file: .env
    depends_on: [ app_db ]

  app_db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data:
    driver: local
