name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: panda-manager-backend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
        
      - name: Create env file
        shell: bash
        run: |
          touch .env
          echo APP_PORT=${{ vars.APP_PORT }} >> .env
          echo MONGO_HOST=${{ vars.MONGO_HOST }} >> .env
          echo MONGO_DB=${{ vars.MONGO_DB }} >> .env
          echo MONGO_CERT=${{ secrets.MONGO_CERT }} >> .env
          echo MONGO_KEY=${{ secrets.MONGO_KEY }} >> .env
          echo MONGO_URL="mongodb+srv://${{ vars.MONGO_HOST }}/${{ vars.MONGO_DB }}?authMechanism=MONGODB-X509&authSource=\\$external&appName=PandaManagerGCP&retryWrites=true&w=majority" >> .env
          echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
          echo OTP_MAIL_HOST=${{ vars.OTP_MAIL_HOST }} >> .env
          echo OTP_MAIL_USER=${{ secrets.OTP_MAIL_USER }} >> .env
          echo OTP_MAIL_PASSWORD=${{ secrets.OTP_MAIL_PASSWORD }} >> .env
          echo OTP_MAIL_PORT=${{ vars.OTP_MAIL_PORT }} >> .env
          echo NODE_ENV=production >> .env
          
      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
