name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: panda-manager-backend

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: panda-manager
          password: ${{ secrets.GH_PAT }}
          logout: false

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
      - name: Create env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_PORT: ${{ vars.APP_PORT }}
          envkey_MONGO_HOST: ${{ vars.MONGO_HOST }}
          envkey_MONGO_DB: ${{ vars.MONGO_DB }}
          envkey_MONGO_CERT: ${{ secrets.MONGO_CERT }}
          envkey_MONGO_KEY: ${{ secrets.MONGO_KEY }}
          envkey_MONGO_URL: "mongodb+srv://${{ vars.MONGO_HOST }}/${{ vars.MONGO_DB }}?authMechanism=MONGODB-X509&authSource=\\$external&appName=PandaManagerGCP&retryWrites=true&w=majority"
          envkey_ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          envkey_OTP_MAIL_HOST: ${{ vars.OTP_MAIL_HOST }}
          envkey_OTP_MAIL_USER: ${{ secrets.OTP_MAIL_USER }}
          envkey_OTP_MAIL_PASSWORD: ${{ secrets.OTP_MAIL_PASSWORD }}
          envkey_OTP_MAIL_PORT: ${{ vars.OTP_MAIL_PORT }}
          envkey_NODE_ENV: production
          directory: ./
          file_name: .env
          fail_on_empty: true
          sort_keys: false
          
      - name: Build and push container image to registry
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
