name: Backend-Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        run: docker build -t panda-manager-backend:latest .
      
      - name: Push Docker image to Docker Hub
        run: docker push panda-manager/backend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Azure CLI
        uses: azure/CLI@v1
        with:
          inlineScript: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      
      - name: Login to Azure
        run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
      
      - name: Deploy to Azure
        run: az webapp container deploy --resource-group YourResourceGroup --name YourWebAppName --docker-registry-server-url https://index.docker.io --docker-registry-server-user yourusername --docker-registry-server-password ${{ secrets.DOCKERHUB_TOKEN }} --docker-custom-image-name yourusername/yourimage:latest
