name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: panda-manager-422520
  GAR_LOCATION: gcr.io
  SERVICE: panda-manager-backend
  REGION: us-central1
  
jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Create .env file
        run: |
          touch .env
          echo APP_PORT=${{ vars.APP_PORT }} >> .env
          echo MONGO_HOST=${{ vars.MONGO_HOST }} >> .env
          echo MONGO_DB=${{ vars.MONGO_DB }} >> .env
          echo MONGO_CERT=${{ secrets.MONGO_CERT }} >> .env
          echo MONGO_KEY=${{ secrets.MONGO_KEY }} >> .env
          echo MONGO_URL="mongodb+srv://${MONGO_HOST}/${MONGO_DB}?authMechanism=MONGODB-X509&authSource=\$external&appName=PandaManagerGCP&retryWrites=true&w=majority" >> .env
          echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
          echo OTP_MAIL_HOST=${{ vars.OTP_MAIL_HOST }} >> .env
          echo OTP_MAIL_USER=${{ secrets.OTP_MAIL_USER }} >> .env
          echo OTP_MAIL_PASSWORD=${{ secrets.OTP_MAIL_PASSWORD }} >> .env
          echo OTP_MAIL_PORT=${{ vars.OTP_MAIL_PORT }} >> .env
          echo NODE_ENV=production >> .env
          
      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"

      # END - Docker auth and build

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
