name: Trigger auto deployment for panda-manager-backend

on:
  push:
    branches:
      [ main ]
      
  # Allow manual trigger 
  workflow_dispatch:

env:
  SERVICE_ACCOUNT: github-action@panda-manager-429621.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/820452924236/locations/global/workloadIdentityPools/github-action/providers/github
  PROJECT_ID: panda-manager-429621
  GAR_LOCATION: europe-southwest1
  REPOSITORY: panda-manager
  SERVICE: backend
  REGION: europe-southwest1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: GCP Login
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push image
        run: |
          docker build . --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
  
  azure-deploy:
    environment: azure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build

    steps:
      - name: GCP Login
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PANDAMANAGERBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PANDAMANAGERBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PANDAMANAGERBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure
        uses: azure/container-apps-deploy-action@v2
        with:
          resourceGroup: PandaManager
          containerAppName: backend
          registryUrl: ${{ env.GAR_LOCATION }}-docker.pkg.dev
          registryUsername: oauth2accesstoken
          registryPassword: ${{ steps.auth.outputs.access_token }}
          imageToDeploy: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          environmentVariables: "APP_URL=${{ vars.APP_URL }} APP_PORT=${{ vars.APP_PORT }} MONGO_HOST=${{ vars.MONGO_HOST }} MONGO_DB=${{ vars.MONGO_DB }} MONGO_URL=mongodb+srv://${{ vars.MONGO_HOST }}/${{ vars.MONGO_DB }}?authMechanism=MONGODB-X509&authSource=$external&appName=PandaManagerGCP&retryWrites=true&w=majority ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} OTP_MAIL_HOST=${{ vars.OTP_MAIL_HOST }} OTP_MAIL_USER=${{ secrets.OTP_MAIL_USER }} OTP_MAIL_PASSWORD=${{ secrets.OTP_MAIL_PASSWORD }} OTP_MAIL_PORT=${{ vars.OTP_MAIL_PORT }} NODE_ENV=production"

  gcp-deploy:
    environment: gcp
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs: build

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
          
      - name: GCP Login
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'backend'
          region: 'europe-southwest1'
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
          env_vars: |-
            APP_URL=${{ vars.APP_URL }}
            APP_PORT=${{ vars.APP_PORT }}
            MONGO_HOST=${{ vars.MONGO_HOST }}
            MONGO_DB=${{ vars.MONGO_DB }}
            MONGO_URL=mongodb+srv://${{ vars.MONGO_HOST }}/${{ vars.MONGO_DB }}?authMechanism=MONGODB-X509&authSource=$external&appName=PandaManagerGCP&retryWrites=true&w=majority
            ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}
            OTP_MAIL_HOST=${{ vars.OTP_MAIL_HOST }}
            OTP_MAIL_USER=${{ secrets.OTP_MAIL_USER }}
            OTP_MAIL_PASSWORD=${{ secrets.OTP_MAIL_PASSWORD }}
            OTP_MAIL_PORT=${{ vars.OTP_MAIL_PORT }}
            NODE_ENV=production
